### ISSUE TITLE
[Discussion] PersistentReactiveDict

### ISSUE THREAD

**Issue by RobertLowe** [RobertLowe/persistent-reactive-dict#1]
Hey,

@pauldowman @rgould what do you guys think? 

Cheers

https://github.com/okgrow/meteor-persistent-session/issues/11

PS: Richard, drink more coffee(script)! :+1:

**Comment by nerdmed** [comment]
Hey Guys, this is a perfect fit for a package i am writing. Would be nice if you could release it soon. I have already implemented the support in my package
[Settings Manger](https://github.com/nerdmed/settings-manager/tree/persistent)

**Comment by nerdmed** [comment]
@RobertLowe if there is anything i can support you with just let me know!

**Comment by RobertLowe** [comment]
hey @nerdmed thanks for checking it out; it's been unreleased, I was hoping some colleagues would check it out firstly. I'll release it soon (today-ish).

Cheers.

**Comment by RobertLowe** [comment]
@nerdmed closing now on atmosphere: http://atmospherejs.com/robertlowe/persistent-reactive-dict
