### ISSUE TITLE
PersistentReactiveDict throwing error "Uncaught TypeError: Class constructor ReactiveDict cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by brettg2** [RobertLowe/persistent-reactive-dict#7]

**Comment by RobertLowe** [comment]
Going to need more context then that

**Comment by brettg2** [comment]
Sorry, this might be a problem with babel and upgrading to Meteor 1.7 (soon to be 1.8). I'll close this out

**Comment by roblingle** [comment]
@brettg2 Was there a change needed to fix this? 

I've upgraded babel to 7.0.0-beta.44 and this is really the only functional issue moving from 1.6.1.1 to 1.8.0.1.

**Comment by roblingle** [comment]
The stack looks like this:
```
TypeError: Class constructor ReactiveDict cannot be invoked without 'new'
    at new PersistentReactiveDict (http://localhost:3000/packages/robertlowe_persistent-reactive-dict.js?hash=63f08000bf6b38ed5b6cfc22e56e7a3b96606344:67:50)
    at Blaze.TemplateInstance.toursBookingsOnCreated (http://localhost:3000/app/app.js?hash=726a1925e65e5b1445e375ce8e78ea55d693e2b7:35189:73)
    at http://localhost:3000/packages/blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:3398:22
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:3769:14)
    at fireCallbacks (http://localhost:3000/packages/blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:3394:12)
    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:3474:5)
    at fireCallbacks (http://localhost:3000/packages/blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:2014:26)
    at Object.Tracker.nonreactive (http://localhost:3000/packages/tracker.js?hash=a9bdf2f732520305683f894b4b4d4d49d90cbe05:626:12)
    at http://localhost:3000/packages/blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:2011:13
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:2271:12) undefined
```

And that point in the code is the CoffeeScript-compiled constructor for PersistentReactiveDict where it errors on line 67 for me (`PersistentReactiveDict.__super__.constructor.apply(this, arguments);`)
```
function PersistentReactiveDict() {
    if (typeof arguments[0] === 'string' && arguments[0].length > 0) {
      this.dictName = arguments[0];
    } else {
      throw new Error("Invalid PersistentReactiveDict argument: '" + arguments[0] + "'");
    }
    if (arguments[1] === 'temporary' || arguments[1] === 'persistent' || arguments[1] === 'authenticated') {
      this.mode = arguments[1];
    } else {
      if (arguments[1] === void 0) {
        this.mode = 'persistent';
      } else {
        throw new Error("Invalid PersistentReactiveDict mode: '" + arguments[0] + "', must be one of: ['temporary', 'persistent', 'authenticated']");
      }
    }
    PersistentReactiveDict.__super__.constructor.apply(this, arguments);
    this.psKeys = {};
    this.psKeyList = [];
    this.psaKeys = {};
    this.psaKeyList = [];
    this.load();
    Tracker.autorun((function(_this) {
      return function() {
        if (Meteor.userId !== void 0 && !Meteor.userId) {
          return _this.clearAuth();
        }
      };
    })(this));
  }
```

**Comment by roblingle** [comment]
And where ReactiveDict comes in is on line 294 where it's the context 

`)(ReactiveDict);`, which means it's coming from here: https://github.com/RobertLowe/persistent-reactive-dict/blob/master/persistent-reactive-dict.coffee#L1

**Comment by roblingle** [comment]
fwiw, I ended up saving the object to the user's profile instead of persisting locally

**Comment by RobertLowe** [comment]
If you can provide a reproduction, I don't mind fixing the issue.

Cheers

**Comment by roblingle** [comment]
Done! Just need to `meteor run` and then view the page.
Thanks for the library.

**Comment by akikodesign** [comment]
hi RobertLowe,

i have got same type issue... when i update meteor version 2.1

![image](https://user-images.githubusercontent.com/5610140/111115442-a11dd500-858a-11eb-9936-a2209219101b.png)


kindly check the print screen

**Comment by RobertLowe** [comment]
@roblingle a little to late, but thanks for the reproduction, I've published a new version and converted the project to typescript.

@akikodesign use 1.0.0 cheers

**Comment by akikodesign** [comment]
i have install this again.. meteor add robertlowe:persistent-reactive-dict
```

You may need these as well:
```
meteor add typescript
meteor add reactive-dict

but showing same error

**Comment by RobertLowe** [comment]
Sounds like you didnt actually get the new version, can you verify your `.meteor/versions` contains `robertlowe:persistent-reactive-dict@1.0.0`? @akikodesign

**Comment by akikodesign** [comment]
robertlowe:persistent-reactive-dict@0.1.2

**Comment by akikodesign** [comment]
> Sounds like you didnt actually get the new version, can you verify your `.meteor/versions` contains `robertlowe:persistent-reactive-dict@1.0.0`? @akikodesign

thanks :) for you great support...
